## 认识异常

程序过程中可能有很多出错的情况，出错的原因可能是多方面的，有的是不可控的内部原因，比如内存不够了、磁盘满了，有的是不可控的外部原因，比如网络连接有问题，更多的可能是程序的编程错误，比如引用变量未初始化就直接调用实例方法。

### 常见的异常
#### NullPointerException (空指针异常)
我们先看一段代码：
```java  
package com.example;
public class ExceptionTest {
    public static void main(String[] args) {
        String s = null;
        s.indexOf("a");
        System.out.println("end");
    }
}
```
变量s没有初始化就调用其实例方法indexOf，运行，屏幕输出为：  
>Exception in thread "main" java.lang.NullPointerException
    at ExceptionTest.main(ExceptionTest.java:5)

输出是告诉我们：在ExceptionTest类的main函数中，代码第5行，出现了空指针异常(java.lang.NullPointerException)。     
**原因：**  
当执行s.indexOf("a")的时候，Java系统发现s的值为null，没有办法继续执行了，这时就启用异常处理机制，首先创建一个异常对象，这里是类NullPointerException的对象，然后查找看谁能处理这个异常，在示例代码中，没有代码能处理这个异常，Java就启用默认处理机制，那就是打印异常栈信息到屏幕，并退出程序。

####
```java
public static void main(String[] arg)  {
    int result= Integer.parseInt("ab3");
    System.out.println("result == " + result);
}
```
